FROM node:18-alpine3.18
RUN npm install -g ts-node ts-node-dev
RUN mkdir -p /home/app
COPY . /home/app
WORKDIR /home/app
EXPOSE 3050
RUN \
  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
  elif [ -f package-lock.json ]; then npm ci; \
  elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm i; \
  else echo "Warning: Lockfile not found. It is recommended to commit lockfiles to version control." && npm install; \
  fi

CMD ["ts-node-dev", "src/index.ts"]
