FROM node:18-alpine3.18
WORKDIR /home/app
COPY . .
EXPOSE 3050
RUN npm install -g ts-node ts-node-dev

CMD [ "sh", "-c", "[ -d node_modules ] && ts-node-dev src/index.ts || (npm ci && ts-node-dev src/index.ts)" ]
